[%
    T = {
        'home'              = "Home",
        'plugins_menu'      = "Extensions",
        'configuration'     = "Configuration",
        'access_username'   = "Electre username",
        'access_password'   = "Electre password",
        'show_resume'       = "Show electre resume",
        'show_image'        = "Show electre image",
        'staff'             = "Staff interface",
        'opac'              = "OPAC",
        'thumbnail_size'    = "Thumbnail size on detail page",
        'yes'               = "Yes",
        'no'                = "No",
        'save_button'       = "Save configuration"
    }
%]
