[%
    T = {
        'home'              = "Accueil",
        'plugins_menu'      = "Extensions",
        'configuration'     = "Configuration",
        'access_username'   = "Nom d'utilisateur Electre",
        'access_password'   = "Mot de passe Electre",
        'show_resume'       = "Afficher le résumé Electre",
        'show_image'        = "Afficher l'image Electre",
        'staff'             = "Interface professionnelle",
        'opac'              = "OPAC",
        'thumbnail_size'    = "Taille miniature sur la page de détail",
        'yes'               = "Oui",
        'no'                = "Non",
        'save_button'       = "Enregistrer la configuration"
    }
%]
